import defaultPic from "../../Images/Default-Profile-Pic.png"; 

export const properties = [
    {
      id: 1,
      imageUrl: defaultPic,
      name: "Test Name",
      role: "Test Role",
      phone: "999,999",
      mail: "Fake mail Address",
      about: "This is about section",
      department: "Test department",
      SocialMediaHandles: "3,000 sq.ft.",
    },
    {
      id: 2,
      imageUrl: defaultPic,
      name: "Test Name",
      role: "Test Role",
      phone: "999,999",
      mail: "Fake mail Address",
      about: "This is about section",
      department: "Test department",
      SocialMediaHandles: "3,000 sq.ft.",
    },
    {
      id: 3,
      imageUrl: defaultPic,
      name: "Test Name",
      role: "Test Role",
      phone: "999,999",
      mail: "Fake mail Address",
      about: "This is about section",
      department: "Test department",
      SocialMediaHandles: "3,000 sq.ft.",
    },
    {
      id: 4,
      imageUrl: defaultPic,
      name: "Test Name",
      role: "Test Role",
      phone: "999,999",
      mail: "Fake mail Address",
      about: "This is about section",
      department: "Test department",
      SocialMediaHandles: "3,000 sq.ft.",
    },
    {
      id: 5,
      imageUrl: defaultPic,
      name: "Test Name",
      role: "Test Role",
      phone: "999,999",
      mail: "Fake mail Address",
      about: "This is about section",
      department: "Test department",
      SocialMediaHandles: "3,000 sq.ft.",
    },
    {
      id: 6,
      imageUrl: defaultPic,
      name: "Test Name",
      role: "Test Role",
      phone: "999,999",
      mail: "Fake mail Address",
      about: "This is about section",
      department: "Test department",
      SocialMediaHandles: "3,000 sq.ft.",
    }
  ];